language: node_js
node_js: stable
os: osx
cache:
  directories:
    - node_modules
install:
  - npm i
script:
  - hexo cl
  - hexo g
after_script:
  - git clone https://${GH_REF} .deploy_git
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git init
  - git config user.name "zeinber"
  - git config user.email "442196841@qq.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
branches:
  only:
  - sourceCode
env:
    global:
        - GH_REF: github.com/zeinber/zeinber.github.io.git