sudo: required
node_js:
  - '12'
cache: npm
install:
  - npm install -g hexo-cli
  - npm install hexo
  - npm install
script:
  - hexo clean
  - hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GH_TOKEN
  target_branch: master
  committer_from_gh: true
  keep_history: true
  on:
    branch: sourceCode